parameters:
    imatic_form.form.type_guesser.genemu.class: Imatic\Bundle\FormBundle\Form\GenemuTypeGuesser
    imatic_form.form.type.date_range.class: Imatic\Bundle\FormBundle\Form\Type\DateRangeType
    imatic_form.form.type.datetime_range.class: Imatic\Bundle\FormBundle\Form\Type\DateTimeRangeType
    imatic_form.form.type.time_range.class: Imatic\Bundle\FormBundle\Form\Type\TimeRangeType
    imatic_form.form.type.range.class: Imatic\Bundle\FormBundle\Form\Type\RangeType
    imatic_form.form.type.ajax_entity_choice.class: Imatic\Bundle\FormBundle\Form\Type\AjaxEntityChoiceType
    imatic_view.form.extension.form_theme.class: Imatic\Bundle\FormBundle\Form\Extension\FormTypeThemeExtension
    imatic_view.form.extension.genemu_jquery_select2_choice: Imatic\Bundle\FormBundle\Form\Extension\GenemuJQuerySelect2ChoiceExtension

services:
    imatic_form.form.type_guesser.genemu:
        class: %imatic_form.form.type_guesser.genemu.class%
        arguments: [@doctrine]
        calls:
            - [ setTranslator, [ @translator ] ]
        tags:
            - { name: form.type_guesser }

    imatic_form.form.type.date_range:
        class: %imatic_form.form.type.date_range.class%
        tags:
            - { name: form.type, alias: imatic_type_date_range }

    imatic_form.form.type.datetime_range:
        class: %imatic_form.form.type.datetime_range.class%
        tags:
            - { name: form.type, alias: imatic_type_datetime_range }

    imatic_form.form.type.time_range:
        class: %imatic_form.form.type.time_range.class%
        tags:
            - { name: form.type, alias: imatic_type_time_range }

    imatic_form.form.type.range:
        class: %imatic_form.form.type.range.class%
        tags:
            - { name: form.type, alias: imatic_type_range }

    imatic_form.form.type.ajax_entity_choice:
        class: %imatic_form.form.type.ajax_entity_choice.class%
        arguments:
            - '@doctrine'
            - '@router'
        tags:
            - { name: form.type, alias: imatic_type_ajax_entity_choice }

    # Form extensions
    imatic_view.form.extension.form_theme:
        class: %imatic_view.form.extension.form_theme.class%
        arguments:
            - '@twig'
        tags:
            - { name: 'form.type_extension', alias: form }

    imatic_view.form.extension.genemu_jquery_select2_choice:
        class: %imatic_view.form.extension.genemu_jquery_select2_choice%
        tags:
            - { name: 'form.type_extension', alias: genemu_jqueryselect2_choice }
