parameters:
    imatic_form.form.type.date_range.class: Imatic\Bundle\FormBundle\Form\Type\DateRangeType
    imatic_form.form.type.datetime_range.class: Imatic\Bundle\FormBundle\Form\Type\DateTimeRangeType
    imatic_form.form.type.time_range.class: Imatic\Bundle\FormBundle\Form\Type\TimeRangeType
    imatic_form.form.type.range.class: Imatic\Bundle\FormBundle\Form\Type\RangeType
    imatic_form.form.type.ajax_choice.class: Imatic\Bundle\FormBundle\Form\Type\AjaxChoiceType
    imatic_form.form.type.ajax_entity_choice.class: Imatic\Bundle\FormBundle\Form\Type\AjaxEntityChoiceType
    imatic_view.form.extension.collection.class: Imatic\Bundle\FormBundle\Form\Extension\CollectionExtension
    imatic_view.form.extension.form_theme.class: Imatic\Bundle\FormBundle\Form\Extension\FormThemeExtension
    imatic_view.form.extension.date.class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
    imatic_view.form.extension.datetime.class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
    imatic_view.form.extension.time.class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
    imatic_view.form.extension.birthday.class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
    imatic_view.form.extension.choice.class: Imatic\Bundle\FormBundle\Form\Extension\ChoiceExtension

services:
    imatic_form.form.type.date_range:
        class: "%imatic_form.form.type.date_range.class%"
        tags:
            - { name: form.type }

    imatic_form.form.type.datetime_range:
        class: "%imatic_form.form.type.datetime_range.class%"
        tags:
            - { name: form.type }

    imatic_form.form.type.time_range:
        class: "%imatic_form.form.type.time_range.class%"
        tags:
            - { name: form.type }

    imatic_form.form.type.range:
        class: "%imatic_form.form.type.range.class%"
        tags:
            - { name: form.type }

    imatic_form.form.type.ajax_choice:
        class: "%imatic_form.form.type.ajax_choice.class%"
        arguments:
            - '%imatic_form.select2%'
            - '@router'
        tags:
            - { name: form.type }

    imatic_form.form.type.ajax_entity_choice:
        class: "%imatic_form.form.type.ajax_entity_choice.class%"
        arguments:
            - '%imatic_form.select2%'
            - '@router'
            - '@doctrine'
        tags:
            - { name: form.type }

    # Form extensions
    imatic_view.form.extension.collection:
        class: "%imatic_view.form.extension.collection.class%"
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    imatic_view.form.extension.form_theme:
        class: "%imatic_view.form.extension.form_theme.class%"
        arguments:
            - '@twig'
            - '%imatic_form.default_theme%'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    imatic_view.form.extension.date:
        class: "%imatic_view.form.extension.date.class%"
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\DateType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }

    imatic_view.form.extension.datetime:
        class: "%imatic_view.form.extension.datetime.class%"
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\DateTimeType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\DateTimeType }

    imatic_view.form.extension.time:
        class: "%imatic_view.form.extension.time.class%"
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\TimeType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\TimeType }

    imatic_view.form.extension.birthday:
        class: "%imatic_view.form.extension.birthday.class%"
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\BirthdayType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\BirthdayType }

    imatic_view.form.extension.choice:
        class: "%imatic_view.form.extension.choice.class%"
        arguments:
            - '@translator'
            - '%imatic_form.select2%'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    # Twig extensions
    imatic_form.twig.extension.form:
        class: Imatic\Bundle\FormBundle\Twig\Extension\FormExtension
        arguments:
            - '@twig.form.renderer'
        tags:
            - { name: 'twig.extension' }
