services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Form types
    Imatic\Bundle\FormBundle\Form\Type\AjaxChoiceType:
        arguments:
            $select2Config: '%imatic_form.select2%'

    Imatic\Bundle\FormBundle\Form\Type\AjaxEntityChoiceType:
        arguments:
            $select2Config: '%imatic_form.select2%'

    # Form extensions
    Imatic\Bundle\FormBundle\Form\Extension\CollectionExtension:
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    Imatic\Bundle\FormBundle\Form\Extension\FormThemeExtension:
        arguments:
            - '@twig.form.renderer'
            - '%imatic_form.default_theme%'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    imatic_form.form.extension.date:
        class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\DateType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }

    imatic_form.form.extension.datetime:
        class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\DateTimeType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\DateTimeType }

    imatic_form.form.extension.time:
        class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\TimeType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\TimeType }

    imatic_form.form.extension.birthday:
        class: Imatic\Bundle\FormBundle\Form\Extension\DatepickerExtension
        arguments:
            - 'Symfony\Component\Form\Extension\Core\Type\BirthdayType'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\BirthdayType }

    Imatic\Bundle\FormBundle\Form\Extension\ChoiceExtension:
        arguments:
            $select2Config: '%imatic_form.select2%'
        tags:
            - { name: 'form.type_extension', extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    # Twig extensions
    Imatic\Bundle\FormBundle\Twig\Extension\FormExtension:
        arguments:
            - '@twig.form.renderer'
        tags:
            - { name: 'twig.extension' }
